### ISSUE TITLE
/=/ and \=/

### ISSUE THREAD

**Issue by asimenio-asteri** [tonsky/FiraCode#1022]
I am a programmer and a chemistry. I use SMILES and I would like these ligatures. sidenote: /=/ is trans and \=/ cis. It is okay if you do not add these, they aren't really programming/maybe they conflict

**Comment by tonsky** [comment]
`/=/` would be a problem in regexps. I’ll think about `\=/`. Thanks!

**Comment by DaveRainbowin** [comment]
thank you agin!

**Comment by RubenVerg** [comment]
Well, IK i am against most people's thoughts here, but
a) A regex which searches for '=' is actually a single token in my mind
b) Editors like VSCode (and all tmLanguage-based ones, AFAIK) separate in tokens, and two different tokens can't ligate. In most langauges, regexes are matched with
```yaml
regex:
  name: constant.regexp.language
  begin: /
  end: (?<!\)/
  captures:
    0:
      name: operator.regexp.language
```
or similarly with a `before`/`end` which tokenizes `begin`, `end` and the things between as three different tokens.
