### ISSUE TITLE
Browser usage seems not to work

### ISSUE THREAD

**Issue by gigioSouza** [tonsky/FiraCode#1157]
I'm trying to add Fira Code to my blog's codeblocks, but it seems not to work.

![image](https://user-images.githubusercontent.com/4052932/99151036-204fda80-2677-11eb-84dc-d8a041fc097a.png)

I'm using [nuxt/content](https://content.nuxtjs.org/) for it, so I'm adding the `woff2` files to my `assets` folder and adding it to my `.scss`

```scss
// Fira Code v5
@font-face {
  font-family: 'Fira Code';
  font-style: normal;
  font-weight: 300 700;
  font-display: swap;
  src: url('~assets/fonts/Fira_Code_v5.2/woff2/FiraCode-VF.woff2') format('woff2-variations');
}
```

It's being loaded, but it seems to not work
![image](https://user-images.githubusercontent.com/4052932/99151107-a2d89a00-2677-11eb-9bb3-13ec1626eb0d.png)

I was hoping to see:
![image](https://user-images.githubusercontent.com/4052932/99151126-c865a380-2677-11eb-84ed-ed3281281ef3.png)
