### ISSUE TITLE
Feasibility of dual color font

### ISSUE THREAD

**Issue by DanielAtKrypton** [tonsky/FiraCode#1161]
4k monitors can display dual color fonts so that when a transparent or translucid background is used, there is no readability penalty, the same strategy used by many subtitle engines. In this regard what about making a dual color FiraCode font?

**Comment by tonsky** [comment]
What do you mean? What would second color be?

**Comment by DanielAtKrypton** [comment]
I believe the default should be white text outlined in black for dark translucent backgrounds for example.
And black outlined white for bright translucent backgrounds, for example.

For subtitles some countries use yellow instead of white.

**Comment by DanielAtKrypton** [comment]
This way, in a completely transparent screen, when the background becomes completely white or completely black, the text can be seen without a problem.

**Comment by tonsky** [comment]
This can be achieved with font rendering, no reason for this to be in the font

**Comment by DanielAtKrypton** [comment]
There is a huge difference from first to second...

![Imgur](https://i.imgur.com/211hYVY.png)

![Imgur](https://i.imgur.com/aryVDQL.png)

Any ideas how to achieve that in windows terminal @tonsky ?

**Comment by tonsky** [comment]
No idea but font is definitely not the answer. Try making a feature request for windows terminal

**Comment by DanielAtKrypton** [comment]
The following result I achieved applying:

- [Fira Code iScript](https://github.com/kencrocken/FiraCodeiScript)
- [VsCode Vibrancy Effect addon](https://github.com/eyhn/vscode-vibrancy)
- [How to add ligatures and cursive fonts to VS Code](https://www.ankursheel.com/blog/add-cursive-fonts-to-vs-code)

Edditing `body` and `.minimap, .editor-scrollable>.decorationsOverviewRuler` of `\.vscode\extensions\eyhn.vscode-vibrancy-1.0.9\themes\Default Dark.css` to:
```CSS
.minimap, .editor-scrollable>.decorationsOverviewRuler {
  opacity: 0.4;
}

body {
  background: transparent !important;
  -webkit-font-smoothing: antialiased;
  -webkit-text-stroke: 0.2px black;
  text-shadow:
  2px   2px   0 black,
  -1px  -1px  0 black,  
  1px   -1px  0 black,
  -1px  1px   0 black,
  1px   1px   0 black;
}
```

And finally setting `renderType` to `dom` in VsCode User `settings.json`:
```json
"terminal.integrated.rendererType": "dom",
```
![Imgur](https://i.imgur.com/NKMYQP5.png)
