### ISSUE TITLE
HTML self-closing tag `/>` issue

### ISSUE THREAD

**Issue by NiklasBr** [tonsky/FiraCode#1269]
Using a regular 1:1 DPI screen on Windows 10. I have a custom style sheet that replaces many `<code>` and such styles with Fira Code, e.g. on GitHub:

```css
.diff-editor *, code, pre {
    font-family: "Fira Code" !important;
    font-size: 10pt;
    font-variant-ligatures: common-ligatures;
    line-height: 1.3 !important;
}
```

<hr>

One issue that happens can be seen in the README here: https://github.com/vuejs/jsx-next where the closing slashes of the tags are almost invisible:

![image](https://user-images.githubusercontent.com/279826/127971843-1b1debf6-619e-4af3-80b5-46957037ee72.png)

<hr>

Computed styles (according to Firefox)
```table
box-sizing: border-box;
color: rgb(0, 92, 197);
font-family: "Fira Code";
font-size: 13.6px;
font-variant-ligatures: common-ligatures;
line-height: 17.6833px;
overflow-wrap: normal;
word-break: normal
```

<hr>

The ligature works in normal sizes elsewhere and is not cut off (so it might perhaps be a Firefox issue)?

Forcing `font-size: 20px;` resolves the issue, but is a bit too large for my taste:
![image](https://user-images.githubusercontent.com/279826/127973027-63998985-4942-4dc2-80d0-50a85f4c9028.png)
