### ISSUE TITLE
Unable to use it in Atom 1.14

### ISSUE THREAD

**Issue by darkcyber** [tonsky/FiraCode#427]
I just install package named "Firacode"

then set Font Family in editor to "Fira Code" doesn't affect my font

font already installed successfully

follow this tutorial https://medium.com/@peterpme/operator-mono-fira-code-the-best-of-both-worlds-191be512fd5e

Doesn't success.

Where i'm doing wrong?

**Comment by ooJerryLeeoo** [comment]
@darkcyber Add this script to your `style.less`:
```less
atom-text-editor {
  font-feature-settings: 'liga' on, 'calt' on;
}
```
