### ISSUE TITLE
Issue with Ruby/CoffeeScript #{} string interpolation

### ISSUE THREAD

**Issue by joshmosh** [tonsky/FiraCode#485]
When using the `"#{}"` string interpolation in Ruby or CoffeeScript (maybe other languages?) the display is off. It looks like it's trying to render the `"#{}"` as `"=>{}"`. I attached a screenshot for reference.

<img width="536" alt="incorrect_string_interpolation" src="https://user-images.githubusercontent.com/34509/29878245-92fb726c-8d67-11e7-9c2b-dba5991c98ef.png">

**Comment by tonsky** [comment]
that’s by design. It’s used in Clojure too. I decided to link them because logically it’s a single token, single unit of meaning: `#{` in that case

**Comment by joshmosh** [comment]
@tonsky Thanks for the response. After looking over the Atom instructions again I added this line to my stylesheet:

```less
atom-text-editor.editor .syntax--constant.syntax--interpolated.syntax--ruby {
  -webkit-font-feature-settings: "liga" off, "calt" off;
}
```

I'm sure the same will work with CoffeeScript.
