### ISSUE TITLE
Proposal: Add support for css variables

### ISSUE THREAD

**Issue by oscarotero** [tonsky/FiraCode#687]
Hi.
It would be nice to have a ligature for `--`, like this:

```css
div {
    --color: blue;
    color: var(--blue);
}

```
